# Generated by Django 4.2.1 on 2023-07-07 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='making',
            field=models.CharField(max_length=1000),
        ),
    ]
