# Generated by Django 4.2.1 on 2023-07-08 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_alter_recipes_making'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='recipe_image',
            field=models.ImageField(default=None, max_length=500, null=True, upload_to='recipess/'),
        ),
    ]
