# Generated by Django 4.2.1 on 2023-07-22 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0003_alter_recipes_recipe_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='chef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chef_name', models.CharField(max_length=100)),
                ('chef_age', models.PositiveIntegerField()),
                ('chef_exp', models.CharField(max_length=500)),
                ('chef_info', models.CharField(max_length=1000)),
                ('chef_img', models.ImageField(default=None, max_length=1000, null=True, upload_to='chefs/')),
                ('recipe_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.recipes')),
            ],
        ),
    ]
