# Generated by Django 4.2.1 on 2023-07-22 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0004_chef'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chef',
            name='chef_img',
            field=models.FileField(default=None, max_length=1000, null=True, upload_to='chefs/'),
        ),
    ]
